# Generated by Django 5.2 on 2025-05-03 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'message de contact',
                'verbose_name_plural': 'messages de contact',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MessageAccueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('media', models.FileField(blank=True, null=True, upload_to='accueil/')),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='portfolio/videos/')),
                ('date', models.DateField()),
                ('resultat', models.TextField(blank=True)),
                ('categorie', models.CharField(choices=[('visuelle', 'Communication Visuelle'), ('digitale', 'Communication Digitale'), ('audiovisuelle', 'Audiovisuelle'), ('evenementielle', 'Événementielle')], max_length=100)),
                ('client', models.CharField(blank=True, max_length=100)),
                ('lien', models.URLField(blank=True)),
                ('en_avant', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icone', models.CharField(max_length=50)),
                ('categorie', models.CharField(choices=[('visuelle', 'Communication Visuelle'), ('digitale', 'Communication Digitale'), ('audiovisuelle', 'Audiovisuelle'), ('evenementielle', 'Événementielle')], max_length=30)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='equipe/')),
                ('bio', models.TextField()),
                ('competences', models.CharField(blank=True, max_length=255)),
                ('lien_linkedin', models.URLField(blank=True)),
                ('lien_twitter', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='blog/')),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('en_avant', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FichierPartage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('fichier', models.FileField(upload_to='clients/fichiers/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
            options={
                'verbose_name': 'fichier partagé',
                'verbose_name_plural': 'fichiers partagés',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
