# Generated by Django 5.2.1 on 2025-05-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projets_user',
            name='status',
            field=models.BooleanField(default=False, help_text='status project.', verbose_name='status'),
        ),
    ]
