# Generated by Django 5.2.1 on 2025-05-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projets_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projets_user',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='clients/fichiers/'),
        ),
    ]
