# Generated by Django 5.2 on 2025-05-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250503_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icone',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/images/'),
        ),
    ]
