# Generated by Django 5.2 on 2025-05-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_service_icone_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='info/')),
                ('lien_linkedin', models.URLField(blank=True)),
                ('lien_twitter', models.URLField(blank=True)),
                ('lien_github', models.URLField(blank=True)),
                ('lien_website', models.URLField(blank=True)),
                ('lien_email', models.EmailField(blank=True, max_length=254)),
                ('lien_telephone', models.CharField(blank=True, max_length=20)),
                ('lien_facebook', models.URLField(blank=True)),
                ('lien_instagram', models.URLField(blank=True)),
                ('lien_youtube', models.URLField(blank=True)),
                ('lien_tiktok', models.URLField(blank=True)),
            ],
        ),
    ]
